services:
  nginx:
    image: nginx:latest
    container_name: wp_site-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/snippets:/etc/nginx/snippets
    depends_on:
      - php
    networks:
      - wp_site-network

  php:
    build: ./docker/php
    container_name: wp_site-php
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:cached
    networks:
      - wp_site-network

  mysql:
    image: mysql:8.0
    container_name: wp_site-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql # Монтируем локальную директорию для хранения данных MySQL
    ports:
      - "7081:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp_site
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - TZ=Europe/Moscow
    networks:
      - wp_site-network

  redis:
    image: redis:latest
    container_name: wp_site-redis
    ports:
      - "6379:6379"
    networks:
      - wp_site-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_site-phpmyadmin
    environment:
      - PMA_HOST=wp_site-mysql
      - PMA_PORT=3306
    ports:
      - "7083:80"
    networks:
      - wp_site-network

  adminer:
    image: adminer
    container_name: wp_site-adminer
    ports:
      - "7082:8080"
    networks:
      - wp_site-network

networks:
  wp_site-network:
    driver: bridge