services:
  nginx:
    image: nginx:latest
    container_name: rwsite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/snippets:/etc/nginx/snippets
    depends_on:
      - php
    networks:
      - rwsite-network

  php:
    build: ./docker/php
    container_name: rwsite-php
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:cached
    networks:
      - rwsite-network

  ftp:
    image: docker.io/delfer/alpine-ftp-server
    container_name: rwsite-ftp
    environment:
      USERS: rwsite|rwsite
      ADDRESS: ftp
    volumes:
      - .:/var/www
    networks:
      - rwsite-network

  mysql:
    image: mysql:8.0
    container_name: rwsite-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql # Монтируем локальную директорию для хранения данных MySQL
    ports:
      - "7081:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rwsite
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - TZ=Europe/Moscow
    networks:
      - rwsite-network

  redis:
    image: redis:latest
    container_name: rwsite-redis
    ports:
      - "6379:6379"
    networks:
      - rwsite-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rwsite-phpmyadmin
    environment:
      - PMA_HOST=rwsite-mysql
      - PMA_PORT=3306
    restart: always
    ports:
      - "7083:80"
    networks:
      - rwsite-network

  adminer:
    image: adminer
    container_name: blog-adminer
    ports:
      - "7082:8080"
    networks:
      - rwsite-network

networks:
  rwsite-network:
    driver: bridge